//
//

//Adds new portrait icon to statdesc.2da
//Will use existing icon with same name and modder prefix
//NOTE: no limit to number of icons that can be added

/*example
LAF d2_portrait_icon INT_VAR name = RESOLVE_STR_REF (@99) STR_VAR bam = ~icon99~ RET icon END

"icon" is number for related opcodes
*/

DEFINE_ACTION_FUNCTION d2_portrait_icon
  INT_VAR name=0
  STR_VAR bam=none prefix=d2
  RET icon
BEGIN

OUTER_SET icon = ~-1~                 // default is no change
ACTION_IF !(GAME_IS ~pstee~) BEGIN    // not used for pstee

  COPY_EXISTING ~STATDESC.2DA~ ~override~

    // Set some variables
    GET_STRREF name iconname
    READ_2DA_ENTRIES_NOW ~statdesc_table~ 1
    COUNT_2DA_ROWS 1 rows
    SET row_count = (rows - 1)    // count starts at 0

    // uses existing icon if found (checks modder prefix)
    FOR (r = 3; r < rows; ++r) BEGIN
      READ_2DA_ENTRY_FORMER ~statdesc_table~ r 1 stringref
      GET_STRREF stringref string
      PATCH_IF (~%string%~ STRING_EQUAL_CASE ~%iconname%~) BEGIN    // if icon name is already used
        READ_2DA_ENTRY_FORMER ~statdesc_table~ r 2 resource
        PATCH_IF !(~%resource%~ STRING_MATCHES_REGEXP ~^%prefix%.*~) BEGIN    // if resource DOES start with "prefix"
          READ_2DA_ENTRY_FORMER ~statdesc_table~ r 0 icon
          SET icon = icon    // RET variable
        END
      END
    END

    // Otherwise, create new icon
    PATCH_IF (icon = ~-1~) BEGIN
      READ_2DA_ENTRY_FORMER ~statdesc_table~ row_count 0 icon    // get last icon number, then add +1
      SET icon += 1    // RET variable
      INSERT_2DA_ROW rows 1 ~%icon% %name% %bam%~    // add new line with variables
      PRETTY_PRINT_2DA
    END
  IF_EXISTS BUT_ONLY

END
END

////////////////////////////////////////////////////////////
